# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

somic <- function(soc_data, mic_vmax, mic_km, kdissolution, kdepoly, kdeath_and_exudates, kdesorb, ksorb, kmicrobial_uptake, cue_0, mcue, mclay, clay, thickness = 23.0, sat = 1.0, max_tsmd = 0.0, use_atsmd = 0L, use_fraction_modern_instead_of_14c_age = 0L, init_spm_14c = 0.0, init_ipm_14c = 0.0, init_doc_14c = 0.0, init_mb_14c = 0.0, init_mac_14c = 0.0, init_soc_14c = NA_real_) {
    .Call(`_SOMic_somic`, soc_data, mic_vmax, mic_km, kdissolution, kdepoly, kdeath_and_exudates, kdesorb, ksorb, kmicrobial_uptake, cue_0, mcue, mclay, clay, thickness, sat, max_tsmd, use_atsmd, use_fraction_modern_instead_of_14c_age, init_spm_14c, init_ipm_14c, init_doc_14c, init_mb_14c, init_mac_14c, init_soc_14c)
}

